package main

import (
	"context"
	"flag"
	"fmt"
	"log/slog"
	"net/http"
	"os"
	"os/signal"
	"strings"
	"syscall"
	"time"

	"github.com/prometheus/client_golang/prometheus/promhttp"

	"github.com/HertzFlow/chain-reconciler/internal/chain"
	"github.com/HertzFlow/chain-reconciler/internal/config"
	"github.com/HertzFlow/chain-reconciler/internal/metrics"
	"github.com/HertzFlow/chain-reconciler/internal/notify"
	"github.com/HertzFlow/chain-reconciler/internal/reconciler"
)

var (
	configPath = flag.String("config", "config.yaml", "path to config.yaml")
	once       = flag.Bool("once", false, "run all reconcilers once and exit (useful for cron mode)")
)

func main() {
	flag.Parse()

	cfg, err := config.Load(*configPath)
	if err != nil {
		fmt.Fprintln(os.Stderr, "config:", err)
		os.Exit(1)
	}

	log := slog.New(slog.NewJSONHandler(os.Stdout, &slog.HandlerOptions{
		Level: parseLevel(cfg.Log.Level),
	}))
	log.Info("chain-reconciler starting",
		"versions", versionNames(cfg),
		"quick_interval", cfg.Scheduler.QuickInterval,
		"daily_at_utc", cfg.Scheduler.DailyAtUTC,
		"once", *once,
	)

	client, err := chain.NewClient(cfg.RPC.URL, cfg.RPC.RequestTimeout)
	if err != nil {
		log.Error("rpc dial failed", "err", err)
		os.Exit(1)
	}
	defer client.Close()

	tasks := []reconciler.Task{
		reconciler.VaultBalances{C: client},
		reconciler.Roles{C: client, RoleNames: cfg.RoleNames},
		reconciler.Timelock{C: client},
		reconciler.MarketParams{C: client},
		reconciler.Fees{C: client},
		reconciler.Funding{C: client},
		reconciler.KeeperGas{C: client, Keepers: cfg.Keepers},
		reconciler.Features{C: client},
		reconciler.Queue{C: client},
		reconciler.MarketOI{C: client},
		reconciler.OracleConfig{C: client},
		reconciler.Chainlink{C: client},
	}

	slack := notify.NewSlack(cfg.SlackWebhookURL())

	if *once {
		runOnce(log, client, cfg, tasks, slack, /*sendSlack=*/ true, /*printDigest=*/ true)
		return
	}

	metrics.ReconcilerUp.Set(1)
	go startMetricsServer(log, cfg.Metrics.Port, cfg.Metrics.Path)

	ctx, cancel := context.WithCancel(context.Background())
	defer cancel()

	// initial run for immediate metric population
	runOnce(log, client, cfg, tasks, slack, /*sendSlack=*/ false, /*printDigest=*/ false)

	go quickLoop(ctx, log, client, cfg, tasks)
	go dailyLoop(ctx, log, client, cfg, tasks, slack)

	sig := make(chan os.Signal, 1)
	signal.Notify(sig, syscall.SIGINT, syscall.SIGTERM)
	<-sig
	log.Info("shutdown signal received")
	metrics.ReconcilerUp.Set(0)
}

func runOnce(log *slog.Logger, client *chain.Client, cfg *config.Config, tasks []reconciler.Task, slack *notify.Slack, sendSlack, printDigest bool) {
	ctx, cancel := context.WithTimeout(context.Background(), 5*time.Minute)
	defer cancel()

	reports := reconciler.RunAll(ctx, log, client, cfg, tasks)
	digest := reconciler.Render(reports)
	log.Info("reconciler run complete", "summary_lines", strings.Count(digest, "\n"))

	if printDigest {
		fmt.Println(digest)
	}
	if sendSlack && slack.Enabled() {
		if err := slack.Send(ctx, digest); err != nil {
			log.Error("slack send failed", "err", err)
		}
	}
}

// quickLoop reruns vault/role/timelock/params at QuickInterval to keep
// metrics fresh between daily digests. No Slack noise here — alerts are
// generated by VictoriaMetrics rules over the resulting metrics.
func quickLoop(ctx context.Context, log *slog.Logger, client *chain.Client, cfg *config.Config, tasks []reconciler.Task) {
	t := time.NewTicker(cfg.Scheduler.QuickInterval)
	defer t.Stop()
	for {
		select {
		case <-ctx.Done():
			return
		case <-t.C:
			runCtx, cancel := context.WithTimeout(ctx, 5*time.Minute)
			reconciler.RunAll(runCtx, log, client, cfg, tasks)
			cancel()
		}
	}
}

// dailyLoop sleeps until the next configured UTC time-of-day and posts a
// digest to Slack with all task findings.
func dailyLoop(ctx context.Context, log *slog.Logger, client *chain.Client, cfg *config.Config, tasks []reconciler.Task, slack *notify.Slack) {
	for {
		next := nextDailyAt(cfg.Scheduler.DailyAtUTC)
		log.Info("daily digest scheduled", "fires_at_utc", next.Format(time.RFC3339))
		select {
		case <-ctx.Done():
			return
		case <-time.After(time.Until(next)):
			runCtx, cancel := context.WithTimeout(ctx, 5*time.Minute)
			reports := reconciler.RunAll(runCtx, log, client, cfg, tasks)
			digest := reconciler.Render(reports)
			if slack.Enabled() {
				if err := slack.Send(runCtx, digest); err != nil {
					log.Error("slack daily send failed", "err", err)
				}
			}
			cancel()
		}
	}
}

func nextDailyAt(hhmm string) time.Time {
	now := time.Now().UTC()
	t, err := time.Parse("15:04", hhmm)
	if err != nil {
		return now.Add(24 * time.Hour)
	}
	target := time.Date(now.Year(), now.Month(), now.Day(), t.Hour(), t.Minute(), 0, 0, time.UTC)
	if !target.After(now) {
		target = target.Add(24 * time.Hour)
	}
	return target
}

func startMetricsServer(log *slog.Logger, port int, path string) {
	mux := http.NewServeMux()
	mux.Handle(path, promhttp.Handler())
	mux.HandleFunc("/health", func(w http.ResponseWriter, _ *http.Request) {
		w.WriteHeader(http.StatusOK)
		_, _ = w.Write([]byte("OK"))
	})
	addr := fmt.Sprintf(":%d", port)
	log.Info("metrics server listening", "addr", addr, "path", path)
	if err := http.ListenAndServe(addr, mux); err != nil {
		log.Error("metrics server stopped", "err", err)
	}
}

func parseLevel(s string) slog.Level {
	switch strings.ToUpper(s) {
	case "DEBUG":
		return slog.LevelDebug
	case "WARN", "WARNING":
		return slog.LevelWarn
	case "ERROR":
		return slog.LevelError
	default:
		return slog.LevelInfo
	}
}

func versionNames(cfg *config.Config) []string {
	out := make([]string, len(cfg.Versions))
	for i, v := range cfg.Versions {
		out[i] = v.Name
	}
	return out
}
